### ISSUE TITLE
Switching from file to folder doesn't update the tabline status

### ISSUE THREAD

**Issue by Dupond** [pacha/vem-tabline#13]
Hello,

Using Vem Tabline, if I open vim with both a file and a folder (e.g. `vim myfile.txt myfolder/`) then "myfile.txt" and "myfolder" are displayed in the tabline, but switching between them (using`:bnext` and `:bprev`) doesn't update the status of the tabline: the folder name always appears as unselected.

Also, is there a way to change the colors of the numbered tabs displayed on the right of the tabline?

Congrats and thanx very much for this great plugin!

Best regards,
Dupond

**Comment by pacha** [comment]
Hi Dupond,

I can't exactly reproduce the behavior you describe. What I see is that the "myfolder" is first displayed but then it disappears when you switch to that buffer. So this behavior is also not very intuitive either but it kind of makes sense: when you open a folder what Vim does is to display its contents using Netrw. Netrw buffers are _unlisted_ and that's why they don't show in the tabline.

The reason why the folder name shows up first is because there's a bit of a glitch: Vim considers the folder name like a new buffer (and a wrong one for the matter due to the trailing slash) until its contents are displayed. At that moment, Netrw kicks in and the buffer is converted to an unnamed one and disappears from the tabline. One alternative, if you don't want this to happen, is to use a file browser plugin that treats the folder as a normal buffer (I personally use https://github.com/jeetsukumaran/vim-filebeagle that doesn't suffer of this problem). However, that may only work if you don't have an special interest in using Netrw in particular.

It can be interesting to know what's your output for `:ls!` before and after displaying the folder contents.

About changing the color of the numbered tabs, just put something like this in your `vimrc` file:
```
highlight VemTablineTabNormal        term=reverse cterm=none ctermfg=0   ctermbg=251 guifg=#242424 guibg=#4a4a4a gui=none
highlight VemTablineTabSelected      term=bold    cterm=bold ctermfg=0   ctermbg=255 guifg=#242424 guibg=#ffffff gui=bold
```
The first line allows you to set the foreground and background of all non-selected tabs, and the second one is for the tab that is selected. `ctermfg`/`ctermbg` are used in 16/256 color terminals while `guifg`/`guibg` are used in the gui version and modern terminals (use `set termguicolors` to enable gui colors in this last case). The colors in the example are grey shades but you can modify them to anything you want.

**Comment by Dupond** [comment]
Thanx very much for the detailed explanations!

First of all I'm really sorry for not having seen that changing the color of the number tabs is already explained in the README *and* in the help file... I think I had symply not seen the difference between `VemTablineNormal` and `VemTablineTabNormal`...

As far as Netrw is concerned, that's not what I see ;) I use Neovim, so maybe that's what makes the difference.

With `vim myfile.txt myfolder`, my Vem Tabline displays:
```
   MYFILE.TXT      myfolder
```
The `myfile.txt` name is highlighted as "selected", and the window is filled with the `myfile.txt` buffer.
`:ls` shows the following:
> 1 %a    "myfile.txt"     line 1
> 2          "myfolder/"    line 0

After one `:bprev` or `:bnext`, the tabline hasn't changed, except that both `myfile.txt` and `myfolder` are highlited as "unselected"; of course, the window displays Netrw Directory Listing; but the `myfolder` name always appears in the tabline.

`:ls` now shows the following:
> 1 #h     "myfile.txt"        line 1
> 2   h     "myfolder"        line 1
> 3u%a-  "[No name]"     line 8

This isn't really an issue; it's just that before using Vem Tabline, I had tested a few plugins with more or less the same functionalities, and I *think* (but I might be wrong) I remember that Netrw was treated as a buffer in the tabline, and could be highlighted; so I had thought I would report it just in case. Of course, this is not critical at all ;) And since you clearly explained that it's the normal Vim behavior, I close the issue.

Thanx for your help!
