### ISSUE TITLE
Let the ability to translate the title of an unnamed buffer

### ISSUE THREAD

**Issue by Dupond** [pacha/vem-tabline#14]
Hello!

For the moment, when a buffer hasn't been saved, its name in the status line appears in the local language (e.g. for me it's `[Aucun nom]` in french), but it also appears in english in the tabline (where it's called `[No Name]`), which makes no sense, since both refer to the same buffer, but with a different "name" (or, to be more precise, indicating that it has no name in two different languages)...

It appears that Vem Tabline defines this name in the `autoload/vem_tabline/buffers.vim` file, on line 119:
```
        " empty name
        if path_parts_count == 0
            let buffer_item.name = '[No Name]'
            continue
        endif
```

So it would be nice if the `buffer_item.name` variable could be configured in the `vimrc` file.

Edit: maybe that's why some plugins with functionalities close to (but not as good as) Vem Tabline choose to use `*` (an asterisk) as a name for an unnamed buffer...

Thanx for your great plugin!

Best regards,
Dupond

**Comment by pacha** [comment]
Hi @Dupond!

Thanks for reporting that. I just changed it to make it configurable. That hardcoded string was rather ugly in any case. Now (since commit 6e64d33a8175cf5f5dcdf7ac26896c20c84f45de) you can set the label that you want to use for unnamed buffers by adding something like:
```
let g:vem_unnamed_buffer_label = '[Aucun nom]'
```
to your `vimrc` file.

J'espère que ça t'aide. Merci beaucoup!

**Comment by Dupond** [comment]
I was just writing (yet another) feature request...

Thank you very much for this commit!  It does help a lot ;)
